### ISSUE TITLE
 generate_csv() failed to work if no ./data/content.csv file was created before

### ISSUE THREAD

**Issue by DiamondMofeng** [fabieu/steam-market-history-exporter#4]
the first time run to generate .csv
![1](https://user-images.githubusercontent.com/52260316/129688541-a7a0797a-c2a8-46da-a9cb-dfe72e8ed9d1.png)

after i created the csv file manually
![2](https://user-images.githubusercontent.com/52260316/129688552-6e6ce427-b4ed-4490-8f21-c49a3ec87a9e.png)

by the way, thanks for your work!This might be the best steam-market-history-exporter i can find,as many of others on github are failed to function.

**Comment by fabieu** [comment]
Hey DiamondMofeng, first of all thanks for reaching out and submitting this issue. I'm currently at work and will look into your merge request later this day.
